betagouv/aplypro

- app/models/student.rb
- app/models/student/mappers/fregata.rb
- app/models/student/mappers/sygne.rb
- db/migrate/20230807153825_add_birthdate_to_students.rb
- db/schema.rb
- spec/factories/students.rb
- spec/models/student_spec.rb
- spec/support/shared/student_mapper.rb
We need to track their age because there are legal differences between paying their legal representant if they are over or under 18. I can't remember what they are but we'll need to draw the distinction.
> students: parse birth date

- app/helpers/dsfr_form_builder.rb
- app/views/ribs/new.html.haml
and remove the heuristic sizing in the form builder as it just cannot work for arbitraty types of values.
> rib: adjust the fields width

- app/controllers/ribs_controller.rb
- app/helpers/dsfr_form_builder.rb
- app/views/ribs/_form.html.haml
- app/views/ribs/edit.html.haml
- app/views/ribs/new.html.haml
- app/views/ribs/show.html.haml
- app/views/students/show.html.haml
- config/locales/fr.yml
- features/saisie_de_coordonnees_bancaires.feature
When payments come into play we'll have to do a whole logic of "don't delete this RIB if it's already been used" etc, but since we don't have them until January just allow editing for now and we'll revisit in time.
> rib: allow editing bank info

- app/controllers/pfmps_controller.rb
- app/views/pfmps/show.html.haml
- config/routes.rb
- spec/requests/pfmps_controller_spec.rb
We weren't scoping the PFMps to the class or establishment that's currently logged in which is bad, and thankfully fixed.
> pfmps: ensure we restrict the scope of managing PFMPs

- app/models/establishment.rb
- db/migrate/20230921092816_add_phone_number_and_email_to_establishments.rb
- db/schema.rb
- spec/models/establishment_spec.rb
We'll need it in case of the payment service needing to reach out to them.
> establishment: parse the phone and email address

- Dockerfile
- README.md
- docker-compose.yml
Salut Stéphane,
J'ai réussi à lancer le projet sur mon pc, après quelques modifications.
Je n'ai pas une grande habitude de Docker, donc je t'ai indiqué en commentaires (que l'on pourra retirer avant de merge) les erreurs que j'ai rencontré dans le `Dockerfile` et le `docker-compose.yml`, pour que tu puisses jeter un coup d'oeil et me dire si ça te va.
Je ne suis pas sûr de la valeur à mettre dans `RUBY_DEBUG_NO_RELINE`, je n'ai pas trouvé de doc à propos de cette variable.
> Init valentin

- app/controllers/home_controller.rb
- app/views/home/legal.html.haml
- app/views/shared/_footer.html.erb
- config/routes.rb
From the osmose task : https://osmose.numerique.gouv.fr/plugins/JTaskPlugin/jsp/redirectTask.jsp?taskId=223680618_JTask
J'avais dicuté vite fait avec mélo des liens du footer, on s'était dit que c'était mieux d'en laisser un seul et de mettre cette page dedans, que de laisser des liens vides
> add legal page

- README.md
- app/helpers/dsfr_form_builder.rb
- app/views/classes/_attributive_decisions_panel.html.haml
- app/views/classes/bulk_pfmp.html.haml
- app/views/classes/show.html.haml
- app/views/home/login.html.haml
- app/views/home/maintenance.html.haml
- app/views/home/welcome.html.haml
- app/views/invitations/index.html.haml
- app/views/pfmps/_dates_warning.html.haml
- app/views/pfmps/index.html.haml
- app/views/pfmps/new.html.haml
- app/views/ribs/_form.html.haml
- app/views/students/show.html.haml
- config/locales/fr.yml
- features/accueil.feature
- features/consultation_des_pfmps.feature
- features/gestion_de_pfmp.feature
- features/premiere_connexion.feature
- features/profil_autorisé.feature
- features/saisie_de_coordonnees_bancaires.feature
- features/step_definitions/perdir_steps.rb
The pptx with all the wordings is in the osmose card :
https://osmose.numerique.gouv.fr/plugins/JTaskPlugin/jsp/redirectTask.jsp?taskId=225060444_JTask
> Wordings from Christel

- app/assets/stylesheets/misc.css
- app/views/layouts/application.html.haml
- app/views/shared/_beta_banner.html.haml
> Beta banner

- app/assets/stylesheets/misc.css
- app/decorators/pfmp_decorator.rb
- app/views/pfmps/_form.html.haml
- app/views/pfmps/_pfmp_badges.html.haml
- app/views/pfmps/_pfmp_student_table.html.haml
- app/views/pfmps/confirm_deletion.html.haml
- app/views/pfmps/show.html.haml
- config/locales/fr-rails.yml
Rapides améliorations sur l'UX des pfmps dont on avait parlé avec Mélo hier
> Tiny ux improvements for pfmp

- features/accueil.feature
- features/consultation_des_listes.feature
- features/décisions_d_attributions.feature
- features/gestion_de_pfmp.feature
- features/saisie_de_coordonnees_bancaires.feature
- spec/factories/classes.rb
Juste pour arrêter de se ballader des "3EME" partout dans nos tests, alors que c'est des lycéens
Il faut en même temps mettre à jour les mock data : https://github.com/betagouv/aplypro-mock-data/pull/4
> wording: use class label '2NDE' in factory & tests

- app/views/home/login.html.haml
> pilotage: manage expectations on login page

- app/models/schooling.rb
- app/models/student.rb
- db/migrate/20231102104302_add_asp_file_reference_to_students.rb
- db/migrate/20231102145756_add_attributive_decision_version_to_schoolings.rb
- db/schema.rb
- lib/attribute_decision_generator.rb
- spec/models/schooling_spec.rb
- spec/models/student_spec.rb
La logique est là mais j'aimerais la documenter un peu mieux
> REBASE attributive decision: add a decision number

- db/seeds.rb
Du coup c'est très très rapide.
> seeds: upsert the mefs

- app/models/concerns/identity_mappers/base.rb
SEP = section d'enseignement professionnel, sounds like us.
> auth: include SEP into the authorised establishment types

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/concerns/identity_mappers/errors.rb
- config/locales/fr.yml
- features/gestion_de_pfmp.feature
- features/premiere_connexion.feature
- features/profil_autorisé.feature
- features/step_definitions/login_steps.rb
* propagation correcte de l'erreur générique d'authentification ;
* mise à jour du message d'erreur ;
* vérification du programme pilote en premier.
Voir la liste des commits pour plus de détails.
> Auth sequence

- app/models/student/mappers/fregata.rb
> fregata: fix the datapath that indicates a student has left

- Guardfile
- app/models/student/mappers/base.rb
- app/models/student/mappers/fregata.rb
- app/models/student/mappers/sygne.rb
- spec/models/student/mappers/fregata_spec.rb
You're not in a class if:
* you've changed class;
* you've changed establishment.
And probably other things, but for now define those two conditions separately and leverage the FREGATA attribute for that.
> student mapper: better logic around a student leaving

- app/views/classes/_alert_apprentices.html.haml
- app/views/classes/index.html.haml
- app/views/classes/show.html.haml
> apprentices: alert message to inform they're not to be considered

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/concerns/identity_mappers/errors.rb
- config/locales/fr.yml
- features/premiere_connexion.feature
This reverts commit fa8d0530d9284c6e22fc1b41d54d7fa5dd839918.
> Revert "auth: remove limited access check in auth process"

- app/jobs/fetch_student_address_job.rb
- app/models/student/address_mappers/fregata.rb
- app/models/student/mappers/fregata.rb
- spec/models/student/address_mappers/fregata_spec.rb
> student: fix crash on missing FREGATA address

- app/models/concerns/identity_mappers/base.rb
- config/locales/faq.yml
- config/locales/fr.yml
- features/step_definitions/delegations_menj.feature
- features/step_definitions/login_steps.rb
- spec/factories/auth.rb
- spec/models/concerns/identity_mappers/base_spec.rb
Closes https://github.com/betagouv/aplypro/issues/177
> Deleg ce implementation

- Procfile
- app/jobs/generate_attributive_decisions_job.rb
- docker-compose.yml
See commit message; closes #178.
> attributive decisions: use a new worker to avoid concurrency issues

- app/models/invitation.rb
- app/views/invitations/new.html.haml
- config/locales/fr.yml
- features/invitations.feature
- spec/models/invitation_spec.rb
Closes https://github.com/betagouv/aplypro/issues/174
> Remove email domain check for invitations

- app/models/classe.rb
- app/views/shared/_header.html.haml
- features/step_definitions/perdir_steps.rb
- spec/models/classe_spec.rb
> students: order active students by last name

- app/models/schooling.rb
- spec/factories/schoolings.rb
- spec/jobs/generate_attributive_decisions_job_spec.rb
- spec/models/schooling_spec.rb
Solves a problem discovered in https://github.com/betagouv/aplypro/issues/207
> Da generation improvements

- app/models/user.rb
- db/migrate/20231130133309_add_index_on_user_email_and_provider.rb
- db/schema.rb
- spec/models/user_spec.rb
Fixes part of https://github.com/betagouv/aplypro/issues/248
> User unicity on email and provider

- app/api/student_api.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/concerns/identity_mappers/base.rb
- app/models/concerns/identity_mappers/cas.rb
- app/models/concerns/identity_mappers/fim.rb
- app/models/establishment.rb
- db/migrate/20231201083922_add_provider_to_establishments.rb
- db/migrate/20231201113835_fill_establishments_students_provider.rb
- db/schema.rb
- features/premiere_connexion.feature
- features/step_definitions/login_steps.rb
- spec/api/student_api/fregata_spec.rb
- spec/api/student_api/sygne_spec.rb
- spec/api/student_api_spec.rb
- spec/factories/establishments.rb
- spec/jobs/fetch_establishment_job_spec.rb
- spec/jobs/fetch_student_address_job_spec.rb
- spec/jobs/fetch_students_job_spec.rb
- spec/models/concerns/identity_mappers/base_spec.rb
- spec/models/establishment_spec.rb
- spec/models/student/mappers/fregata_spec.rb
- spec/models/student/mappers/sygne_spec.rb
Closes https://github.com/betagouv/aplypro/issues/138
> Update role on login and add provider and ministry to establishments

- app/controllers/home_controller.rb
- app/controllers/ribs_controller.rb
- app/views/ribs/confirm_deletion.html.haml
- app/views/students/show.html.haml
- config/locales/fr.yml
- config/routes.rb
- features/saisie_de_coordonnees_bancaires.feature
- spec/requests/ribs_controller_spec.rb
We'll have to make sure this isn't confused with "updating with a new RIB" once we start payments, because we want to trace the history of the RIBs they've used.
> ribs: allow deleting RIBs

- app/controllers/home_controller.rb
- app/models/mef.rb
- app/models/wage.rb
- db/mef_seeder.rb
- db/migrate/20231208091401_add_mef_code_to_wages.rb
- db/schema.rb
- db/seeds.rb
- db/wage_seeder.rb
- features/step_definitions/perdir_steps.rb
- spec/factories/mefs.rb
- spec/factories/wages.rb
- spec/models/mef_spec.rb
- spec/models/wage_spec.rb
Closes https://github.com/betagouv/aplypro/issues/227
> Fix mef amounts

- app/models/concerns/identity_mappers/base.rb
- features/premiere_connexion.feature
- features/step_definitions/perdir_steps.rb
Closes https://github.com/betagouv/aplypro/issues/293
> auth: Sentry log when establishment tries to update student_provider

- app/jobs/fetch_establishment_job.rb
- app/models/establishment.rb
- spec/jobs/fetch_establishment_job_spec.rb
Closes https://github.com/betagouv/aplypro/issues/291
> Avoir crashing on empty establishments

- app/models/classe.rb
- app/views/classes/show.html.haml
- features/consultation_des_listes.feature
- features/premiere_connexion.feature
- features/step_definitions/perdir_steps.rb
- features/step_definitions/web_steps.rb
- spec/models/classe_spec.rb
Closes https://github.com/betagouv/aplypro/issues/272
> Sort students in classe show

- app/assets/stylesheets/misc.css
- app/controllers/classes_controller.rb
- app/views/classes/bulk_pfmp_completion.html.haml
- app/views/classes/show.html.haml
- app/views/pfmps/_form.html.haml
- app/views/shared/_flash.html.haml
- config/locales/fr.yml
- config/routes.rb
- features/completion_de_pfmps.feature
- features/gestion_de_pfmp.feature
- features/step_definitions/perdir_steps.rb
- features/step_definitions/web_steps.rb
Closes https://github.com/betagouv/aplypro/issues/252
> Ux complete pfmps

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/concerns/identity_mappers/base.rb
- features/step_definitions/delegations_menj.feature
Closes https://github.com/betagouv/aplypro/issues/305
> Deleg ce users fetch establishment data

- app/controllers/establishments_controller.rb
- app/views/establishments/_select_form.html.haml
- app/views/establishments/select.html.haml
- app/views/shared/_etab_banner.html.haml
- app/views/users/omniauth_callbacks/select_etab.html.haml
- config/routes.rb
- features/premiere_connexion.feature
Closes https://github.com/betagouv/aplypro/issues/283
> establishment: select page

- app/controllers/students_controller.rb
- app/views/pfmps/_pfmp_student_table.html.haml
- app/views/students/show.html.haml
- features/gestion_de_pfmp.feature
- features/step_definitions/perdir_steps.rb
Closes https://github.com/betagouv/aplypro/issues/263
> Don't show pfmps from other establishments in student show

- app/controllers/home_controller.rb
- app/helpers/home_helper.rb
- app/views/home/_home_timeline.html.haml
- features/accueil.feature
- features/step_definitions/home_steps.rb
- features/step_definitions/perdir_steps.rb
Closes https://github.com/betagouv/aplypro/issues/321
> Home : pfmps indicators should not count closed schoolings

- app/controllers/classes_controller.rb
- app/controllers/ribs_controller.rb
- app/views/classes/bulk_pfmp_completion.html.haml
- app/views/classes/show.html.haml
- app/views/ribs/missing.html.haml
- config/locales/fr.yml
- config/routes.rb
- features/completion_de_pfmps.feature
- features/gestion_de_pfmp.feature
- features/saisie_de_coordonnées_bancaires_manquantes_pour_une_classe.feature
- features/step_definitions/perdir_steps.rb
- features/step_definitions/rib_steps.rb
- features/step_definitions/web_steps.rb
Closes https://github.com/betagouv/aplypro/issues/253
> Ux rib input for a classe

- app/assets/stylesheets/dsfr-overrides.css
- app/assets/stylesheets/misc.css
- app/controllers/establishments_controller.rb
- app/helpers/home_helper.rb
- app/models/concerns/user_authorisation.rb
- app/models/establishment.rb
- app/models/establishment_user_role.rb
- app/models/user.rb
- app/views/classes/_attributive_decisions_panel.html.haml
- app/views/home/_attributive_decision_form.html.haml
- app/views/home/_home_timeline.html.haml
- config/locales/fr.yml
- db/migrate/20240104143944_add_confirmed_director_to_establishment.rb
- db/schema.rb
- features/décisions_d_attributions.feature
- features/step_definitions/home_steps.rb
- features/step_definitions/web_steps.rb
- lib/attribute_decision_generator.rb
- spec/factories/establishments.rb
- spec/factories/users.rb
- spec/models/establishment_spec.rb
- spec/models/establishment_user_role_spec.rb
- spec/models/schooling_spec.rb
- spec/models/user_spec.rb
- spec/requests/establishments_controller_spec.rb
Closes https://github.com/betagouv/aplypro/issues/277
> Only a confirmed director can generate Attributive decisions

- app/api/student_api/base.rb
- app/jobs/fetch_student_information_job.rb
- app/jobs/generate_attributive_decision_job.rb
- app/models/student.rb
- app/models/student/info_mappers/base.rb
- app/models/student/info_mappers/fregata.rb
- app/models/student/info_mappers/sygne.rb
- app/models/student/mappers/fregata.rb
- db/migrate/20240108010009_add_birth_attributes_to_students.rb
- db/migrate/20240108140328_add_biological_sex_to_students.rb
- db/schema.rb
- spec/jobs/fetch_student_information_job_spec.rb
- spec/jobs/generate_attributive_decision_job_spec.rb
- spec/models/student/info_mappers/fregata_spec.rb
- spec/models/student/info_mappers/sygne_spec.rb
- spec/models/student_spec.rb
Repurpose the address-fetching job to a more "get all the extra" info kind of job.
> Extra info job

- app/controllers/home_controller.rb
Fixes Sentry issue # 80369
Closes #351.
> home: harden badge for when count > total

- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users_controller.rb
- app/models/concerns/user_authorisation.rb
- app/views/shared/_header.html.haml
- spec/requests/establishments_controller_spec.rb
Closes https://github.com/betagouv/aplypro/issues/349
> Redirect to establishment selection when user.establishment is empty

- app/assets/stylesheets/misc.css
- app/controllers/classes_controller.rb
- app/controllers/concerns/role_check.rb
- app/controllers/establishments_controller.rb
- app/controllers/validations_controller.rb
- app/decorators/pfmp_decorator.rb
- app/helpers/application_helper.rb
- app/helpers/menu_helper.rb
- app/helpers/ribs_helper.rb
- app/helpers/schoolings_helper.rb
- app/models/mef.rb
- app/views/classes/bulk_pfmp_completion.html.haml
- app/views/classes/show.html.haml
- app/views/home/_home_timeline.html.haml
- app/views/pfmps/_pfmp_student_table.html.haml
- app/views/shared/_header.html.haml
- app/views/validations/index.html.haml
- app/views/validations/show.html.haml
- config/locales/fr.yml
- config/routes.rb
- features/validation_de_pfmps.feature
- spec/models/mef_spec.rb
Closes https://github.com/betagouv/aplypro/issues/256
> validation: validate pfmps per class

- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users_controller.rb
- app/helpers/home_helper.rb
- app/models/concerns/user_authorisation.rb
- app/models/user.rb
- app/views/users/_select_establishment_form.html.haml
- db/migrate/20240117162049_rename_user_establishment_to_selected_establishment.rb
- db/schema.rb
- features/step_definitions/perdir_steps.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/establishments_controller_spec.rb
- spec/requests/users_controller_spec.rb
Long overdue: this attribute only indicates the current establishment being driven by the user, so rename accordingly.
> user: rename establishment to selected establishment

- Guardfile
- app/controllers/ribs_controller.rb
- features/saisie_de_coordonnées_bancaires_manquantes_pour_une_classe.feature
- spec/requests/ribs_controller_spec.rb
Closes https://github.com/betagouv/aplypro/issues/379
> ribs: Fix IDOR vulnerability

- app/views/validations/index.html.haml
- config/locales/fr.yml
- features/validation_de_pfmps.feature
Closes https://github.com/betagouv/aplypro/issues/386
> validations: coherent design in class list

- app/controllers/application_controller.rb
- app/controllers/classes_controller.rb
- app/controllers/establishments_controller.rb
- app/controllers/validations_controller.rb
- app/helpers/classes_helper.rb
- app/helpers/home_helper.rb
- app/jobs/generate_missing_attributive_decisions_job.rb
- app/models/classe.rb
- app/models/concerns/classes_indicators.rb
- app/models/establishment.rb
- app/models/pfmp.rb
- app/views/classes/index.html.haml
- app/views/validations/index.html.haml
Closes https://github.com/betagouv/aplypro/issues/389
> Optimize class indicator requests

- app/models/concerns/identity_mappers/base.rb
Closes https://github.com/betagouv/aplypro/issues/394
> establishments: add EME type

- app/controllers/pfmps_controller.rb
- app/models/concerns/allowance_checker.rb
- app/models/pfmp.rb
- app/models/student.rb
- spec/factories/mefs.rb
- spec/factories/pfmps.rb
- spec/factories/wages.rb
- spec/models/concerns/allowance_checker_spec.rb
- spec/models/pfmp_spec.rb
The allowance is per MEF per year per student.
> pfmp: rework the allowance check

- app/services/asp/mappers/dossier_mapper.rb
- app/services/asp/mappers/enregistrement_mapper.rb
- app/services/asp/mappers/prestadoss_mapper.rb
- lib/asp/entities/dossier.rb
- lib/asp/entities/enregistrement.rb
- lib/asp/entities/entity.rb
- lib/asp/entities/prestadoss.rb
- spec/lib/asp/entities/dossier_spec.rb
- spec/lib/asp/entities/enregistrement_spec.rb
- spec/lib/asp/entities/prestadoss_spec.rb
- spec/services/asp/mappers/dossier_mapper_spec.rb
See commit log 🤸 https://github.com/betagouv/aplypro/commit/6c5464cc1f36b86e358b8cb60769f29ec01d4d6f
> asp: ensure we pass along the ASP object references

- Gemfile
- Gemfile.lock
https://github.com/fringd/zipline/pull/93#issuecomment-1924909275
> No need to use the zipline fork anymore, it has been merged.

- README.md
En vue de la passation, je commence à préparer la documenation nécessaire.
> improve readme with vocabulary

- app/models/establishment.rb
- features/anciens_eleves.feature
- features/step_definitions/student_steps.rb
- features/step_definitions/web_steps.rb
Closes https://github.com/betagouv/aplypro/issues/446
> Fix DA generation for closed schoolings

- db/migrate/20240219100348_add_administrative_number_to_schoolings.rb
> db: optimise the latest migration

- Makefile
- app/views/pfmps/show.html.haml
- config/cucumber.yml
- features/paiements.feature
- features/retour_des_paiments.feature
it's too early to display anything yet.
> payments: mask the UI

- db/migrate/20240228153920_remove_payments.rb
We have 30 minutes to deploy on Scalingo before the process is killed. That yields 1800 seconds to update ~300K payment->pfmp records, hence 0.06s per update which is just not doable.
Rework the migration and:
1. do the appropriate joins to avoid re-querying ;
2. map each batch to its PFMP with the amount updated ;
3. upsert them all.
This should be much faster and leaves time for the other bit to happen, updating each payment which has payment requests attached to it. At the time of writing, there are only 14,632 payments with attached requests on production so it leaves us a fair bit of time to make the change.
> db: optimise the payment migrations

- config/locales/faq.yml
> fix typo in faq

- app/models/asp/payment_request.rb
- app/models/pfmp.rb
- app/views/pfmps/show.html.haml
- features/paiements.feature
- features/retour_des_paiments.feature
- features/step_definitions/paiement_steps.rb
- features/step_definitions/perdir_steps.rb
- features/step_definitions/web_steps.rb
Closes https://github.com/betagouv/aplypro/issues/550
> pfmp: prevent alteration of pfmps with ongoing payment requests

- app/controllers/home_controller.rb
- app/views/home/accessibility.html
- app/views/shared/_footer.html.erb
- config/routes.rb
Made with https://betagouv.github.io/a11y-generateur-declaration
> footer: generate the accesibility page

- app/models/pfmp.rb
- app/views/pfmps/show.html.haml
- config/initializers/version.rb
https://sentry.incubateur.net/organizations/betagouv/issues/91210/events/ffc1f33eb4724d539052e4dd0d705c13/?project=109
> Fix pfmp show for zero amount

- config/initializers/content_security_policy.rb
- config/initializers/permissions_policy.rb
There's a new newline-after-magit-comment rule apparently
> lint: Rubocop updates

- lib/asp/entities/pers_physique.rb
- spec/lib/asp/entities/pers_physique_spec.rb
> asp: don't send the codeinseecommune if the student is born abroad

- app/views/home/login.html.haml
- config/initializers/omniauth.rb
- config/initializers/version.rb
- config/routes.rb
see: https://github.com/betagouv/aplypro/pull/624/commits/f41623524ef994795a24e44e2b3c590250e8d7b4
> config: restore the `/users` routes

- app/controllers/asp/schoolings_controller.rb
- app/models/pfmp.rb
- app/services/asp/mappers/prestadoss_mapper.rb
- app/views/asp/schoolings/_pfmps.html.haml
- app/views/asp/schoolings/_schooling.html.haml
- app/views/asp/schoolings/index.html.haml
- features/asp_consultation_de_dossier.feature
Closes https://github.com/betagouv/aplypro/issues/635
> Improve asp UI

- app/assets/stylesheets/misc.css
- app/facades/establishment_facade.rb
- app/helpers/application_helper.rb
- app/helpers/payment_requests_helper.rb
- app/helpers/pfmps_helper.rb
- app/models/asp/payment_request.rb
- app/models/establishment.rb
- app/views/classes/index.html.haml
- app/views/home/_home_timeline.html.haml
- app/views/validations/index.html.haml
- app/views/validations/show.html.haml
- config/locales/fr.yml
- features/acceuil_status_des_paiements.feature
- features/accueil.feature
- features/paiements.feature
- features/profil_autorisé_menj.feature
- features/retour_des_paiments.feature
- features/step_definitions/home_steps.rb
- features/step_definitions/login_steps.rb
- features/step_definitions/paiement_steps.rb
- features/step_definitions/student_steps.rb
- features/support/asp.rb
- spec/facades/establishment_facade_spec.rb
- spec/factories/asp/payment_requests.rb
Closes https://github.com/betagouv/aplypro/issues/574
> Display payments status in home page

- app/controllers/application_controller.rb
- app/controllers/asp/application_controller.rb
- app/controllers/concerns/user_logger.rb
L'idée c'est de pouvoir en production savoir quel utilisateur a fait quel action, si il y a besoin un jour de tracker une attaque ou quoi que ce soit qui mérite de savoir qui fait quoi.
> logs: Add user id log at info level

- app/models/rib.rb
- config/initializers/sepa_countries.rb
- config/initializers/version.rb
- config/locales/fr.yml
- data/sepa-zone-countries.csv
- features/saisie_de_coordonnees_bancaires.feature
- spec/lib/payment_fixer_spec.rb
- spec/models/rib_spec.rb
- spec/services/asp/mappers/coord_paie_mapper_spec.rb
And normalize them as well by stripping leading and trailing whitespaces.
Closes #619.
> ribs: validate RIBs against the SEPA zone

- app/models/pfmp.rb
- config/locales/fr.yml
- features/anciens_eleves.feature
- features/calcul_des_montants.feature
- features/completion_de_pfmps.feature
- features/gestion_de_pfmp.feature
- features/paiements.feature
- features/step_definitions/pfmp_steps.rb
- features/validation_en_masse_de_pfmps.feature
- spec/lib/asp/entities/entities_integration_spec.rb
- spec/models/concerns/pfmp_amount_calculator_spec.rb
- spec/models/pfmp_spec.rb
> pfmp: ensure the day count fits within the start/end dates

- README.md
J'ai cherché cette valeur beaucoup trop longtemps, donc je documente.
> readme: Documentation of a special access identity attribute

- app/models/rib.rb
- app/services/asp/mappers/coord_paie_mapper.rb
- lib/asp/entities/coord_paie.rb
- spec/lib/asp/entities/coord_paie_spec.rb
- spec/models/rib_spec.rb
- spec/services/asp/mappers/coord_paie_mapper_spec.rb
> rib: remove more offending characters

- Gemfile
- Gemfile.lock
- app/jobs/send_payment_requests_job.rb
- app/models/asp/errors.rb
- app/models/asp/payment_request.rb
- app/models/asp/request.rb
- db/migrate/20240415110650_add_not_null_constraint_for_payment_requests_pfmp.rb
- db/schema.rb
- features/step_definitions/paiement_steps.rb
- features/support/asp.rb
- spec/jobs/send_payment_requests_job_spec.rb
- spec/models/asp/request_spec.rb
- spec/rails_helper.rb
Closes #643, and also observe the max upload count + max requests per week limits.
> asp: max request size

- config/environments/production.rb
You can turn it off with bin/rails c --no-sandbox.
> config: active sandbox mode by default in production

- lib/asp/entities/dossier.rb
- lib/asp/entities/prestadoss.rb
- spec/lib/asp/entities/dossier_spec.rb
- spec/lib/asp/entities/prestadoss_spec.rb
> Validate dossier mer

- app/jobs/send_payment_requests_job.rb
- spec/jobs/send_payment_requests_job_spec.rb
fix the auto-limiting of requests by including the MAX_RECORDS_PER_FILE into the limit calculation, which means the number of request is always under the number of requests left, the number of records per file and what you're actually trying to send which covers all use-cases.
> asp: fix the request limiting

- db/schema.rb
Apparently I forgot to check it into
https://github.com/betagouv/aplypro/pull/787/commits/7ee8844e8427ab0ad9a6a461c45710052da38135
> db: fix the schema

- app/controllers/ribs_controller.rb
- app/models/rib.rb
- app/views/asp/schoolings/_schooling.html.haml
- app/views/ribs/_form.html.haml
- app/views/ribs/missing.html.haml
- config/locales/fr.yml
- db/migrate/20240503100542_add_type_on_rib.rb
- db/schema.rb
- features/asp_consultation_de_dossier.feature
- spec/factories/ribs.rb
- spec/factories/students.rb
- spec/models/asp/payment_request_state_machine_spec.rb
Closes https://github.com/betagouv/aplypro/issues/836
> rib: expand Rib owner type to an enum

- Gemfile
- Gemfile.lock
- app/jobs/send_payment_requests_job.rb
- config/schedule.rb
- cron.json
- docs/tâches_automatisées.md
- lib/tasks/schedule.rake
Une implémentation possible de #814.
> schedule: add a way to easily write/generate schedules

- app/views/pfmps/_create_payment_request.html.haml
- features/suivi_des_pfmps_par_les_directeurs.feature
> Prevent display of recreate p_r button in case of unpaid

- app/services/asp/mappers/coord_paie_mapper.rb
- config/initializers/version.rb
- spec/services/asp/mappers/coord_paie_mapper_spec.rb
> Manage the validity of BIC codes

- cron.json
Forgot to actually update the file when we changed `every :day` to `every :weekday`.
> schedule: regenerate

- app/models/asp/payment_request_state_machine.rb
- features/suivi_des_pfmps_par_les_directeurs.feature
> Revert "Ajout de l'état "unpaid" dans les états "retryable" "

- app/apis/students_api/sygne/api.rb
- app/apis/students_api/sygne/mappers/schooling_mapper.rb
- app/models/student/mappers/base.rb
- app/models/student/mappers/fregata.rb
- app/services/updaters/student_schoolings_updater.rb
- spec/apis/students_api/sygne/api_spec.rb
- spec/apis/students_api/sygne/mappers/schooling_mapper_spec.rb
- spec/services/updaters/student_schoolings_updater_spec.rb
- spec/support/webmock_helpers.rb
* don't raise errors when student type is unknown
* also fix the listing mappers to not return an instanciated mapper.
> mappers: various leftover fixes

- app/models/asp/payment_request.rb
- app/models/asp/payment_request_state_machine.rb
- app/models/establishment.rb
- app/services/pfmp_manager.rb
- db/migrate/20240529093337_add_rib_field_to_asp_payment_resquest_table.rb
- db/schema.rb
- spec/models/asp/payment_request_spec.rb
- spec/models/asp/payment_request_validator_spec.rb
> add rib to asp_payment_request

- app/jobs/concerns/document_generation.rb
- app/jobs/generate_abrogation_decision_job.rb
- app/jobs/generate_attributive_decision_job.rb
- db/migrate/20240603124726_add_abrogation_decision_version_to_schooling.rb
- db/schema.rb
- spec/jobs/generate_abrogation_decision_job_spec.rb
> Abrogation: Jobs

- db/migrate/20240529093337_add_rib_field_to_asp_payment_resquest_table.rb
- db/schema.rb
- disable transactional behavior
- concurrent indexing
> Fix migration to prevent downtime

- app/jobs/fetch_students_job.rb
- In case the establishment has been deleted for instance
> Discard jobs that should be dead

- app/views/pfmps/_payment_requests_history.html.haml
> Display updated_at of last transition in p_r history

- app/models/establishment.rb
Hotfix to unblock the sending of payments
> Add contract type 60

- app/jobs/application_job.rb
- app/jobs/concerns/document_generation.rb
- app/jobs/concerns/fregata_proof.rb
- app/jobs/fetch_student_schoolings_information_job.rb
- app/jobs/fetch_students_job.rb
- app/jobs/generate_attributive_decision_job.rb
- app/jobs/prepare_payment_request_job.rb
- More minor fixes to fetch actual schoolings dates
> Fregata proofing

- app/controllers/schoolings_controller.rb
- app/jobs/concerns/fregata_proof.rb
- app/jobs/fetch_student_schoolings_information_job.rb
- app/jobs/fetch_students_job.rb
- app/jobs/generate_abrogation_decision_job.rb
- app/models/asp/payment_request_validator.rb
- app/views/classes/_students_table.html.haml
- app/views/pfmps/_create_payment_request.html.haml
- app/views/pfmps/_retry_incomplete_payment_request.html.haml
- app/views/pfmps/show.html.haml
- app/views/schoolings/confirm_abrogation.html.haml
- app/views/shared/_confirmed_director.html.haml
- app/views/students/show.html.haml
- app/views/validations/show.html.haml
- config/locales/fr.yml
- config/routes.rb
- features/décisions_d_attributions.feature
- features/step_definitions/perdir_steps.rb
- spec/jobs/generate_abrogation_decision_job_spec.rb
- spec/models/asp/payment_request_validator_spec.rb
- spec/requests/schoolings_controller_spec.rb
> Conditional abrog DA (Abrog DA interface part 2)

- app/models/establishment.rb
> Allow cont etab

- app/models/asp/payment_request_validator.rb
- config/locales/fr.yml
- spec/models/asp/payment_request_validator_spec.rb
> Allow payment of moral person rib

- app/controllers/classes_controller.rb
- app/models/classe.rb
> Fix UI end_date/start_date check

- app/controllers/classes_controller.rb
- app/jobs/fetch_student_information_job.rb
- spec/factories/pfmps.rb
Closes [#382](https://github.com/betagouv/aplypro/issues/382)
+ other fixes
> Rand fixes

- app/models/asp/payment_request_validator.rb
- app/models/student.rb
- spec/models/asp/payment_request_validator_spec.rb
> Fix adult rib validation in payment request validator

- app/jobs/janitor_job.rb
- app/jobs/sync/student_schoolings_job.rb
- app/models/pfmp.rb
- app/models/rib.rb
- app/models/schooling.rb
- app/models/stats/main.rb
- config/initializers/version.rb
- config/locales/fr.yml
- spec/factories/schoolings.rb
- spec/models/asp/payment_request_validator_spec.rb
- spec/models/rib_spec.rb
- spec/models/schooling_spec.rb
> Change definition of a closed schooling

- app/models/asp/payment_return.rb
- app/services/asp/readers/csv_reader.rb
- app/services/asp/readers/integrations_file_reader.rb
- app/services/asp/readers/payments_file_reader.rb
- app/services/asp/readers/rejects_file_reader.rb
Why? Because we skipped 1 return with double INE
> Make return jobs replayable + Remove debug util

- app/models/asp/errors.rb
- app/models/asp/payment_request_validator.rb
- app/models/establishment.rb
- app/models/student.rb
- app/services/asp/mappers/adresse_mapper.rb
- config/locales/fr.yml
- features/accueil_status_des_paiements.feature
- features/step_definitions/payment_requests_steps.rb
- features/step_definitions/student_steps.rb
- features/suivi_des_pfmps_par_les_directeurs.feature
- lib/asp/entities/adresse.rb
- spec/decorators/asp/payment_request_decorator_spec.rb
- spec/factories/asp/payment_requests.rb
- spec/factories/establishments.rb
- spec/lib/asp/entities/adresse_spec.rb
- spec/models/asp/payment_request_spec.rb
- spec/models/asp/payment_request_state_machine_spec.rb
- spec/models/asp/payment_request_validator_spec.rb
- spec/requests/schoolings_controller_spec.rb
> Allow payments for students living abroad using the establishment's address

- app/facades/classes_facade.rb
Tech debt (noticed via Sentry)
> Fix n+1 query on Classes#index + show

- app/models/mef.rb
- db/mef_seeder.rb
- db/migrate/20240814133039_add_school_year_to_mef.rb
- db/schema.rb
- spec/factories/mefs.rb
> Attach Mefs to SchoolYears

- app/helpers/dsfr_form_builder.rb
- app/views/ribs/_owner_type.html.haml
- app/views/ribs/missing.html.haml
- config/locales/fr.yml
- features/saisie_de_coordonnées_bancaires_manquantes_pour_une_classe.feature
- features/step_definitions/rib_steps.rb
> Enhance RIBs form

- app/models/pfmp_state_machine.rb
To merge only when test in staging is successful (so far not really)
> Activate indus feature in production

- app/apis/students_api/csv/mappers/student_mapper.rb
Correct inversion of name/last-name in importer
> Fix last_name/first_name

- app/controllers/schoolings_controller.rb
- app/helpers/classes_helper.rb
- app/jobs/sync/student_schoolings_job.rb
- app/models/classe.rb
- app/models/schooling.rb
- app/views/classes/_students_removed_table.html.haml
- app/views/classes/show.html.haml
- app/views/pfmps/_pfmp_student_table.html.haml
- app/views/schoolings/_student_informations.html.haml
- app/views/schoolings/confirm_removal.html.haml
- app/views/schoolings/confirm_removal_cancellation.html.haml
- app/views/students/show.html.haml
- config/locales/fr.yml
- config/routes.rb
- db/migrate/20240925131116_add_removed_at_to_schoolings.rb
- db/schema.rb
- features/1_scolarite.feature
- spec/models/schooling_spec.rb
Bouton pour retirer l'élève de la classe : ![image](https://github.com/user-attachments/assets/e9bdfd0c-de1e-4158-a640-138266b6748c)
Menu pour confirmer le retrait de l'élève de la classe : ![image](https://github.com/user-attachments/assets/0a6e55c1-272d-4ddd-9d34-bd13be994c05)
Affichage dans la liste des élèves d'une classe du tableau des élèves retirés : ![image](https://github.com/user-attachments/assets/ac071530-b585-44c0-b1c8-3c4322d97f17)
Menu pour confirmer la réintégration de l'élève dans la classe : ![image](https://github.com/user-attachments/assets/435d79bf-88c4-4d68-bb9f-b547372a7cc5)
> Interface pour marquer les élèves non admis pour les directeurs

- README.md
- lib/asp/entities/adresse.rb
- support/overrides.rb
Add a file that can be edited to add utilities for support to debug records in a Production console.
> Add support overrides file to be loaded in console

- app/apis/students_api/fregata/mappers/schooling_mapper.rb
- app/models/student/mappers/base.rb
- app/models/student/mappers/fregata.rb
- app/models/student/mappers/sygne.rb
> Add update of schooling attributes upon class list refresh

- app/models/asp/payment_request.rb
- app/views/pfmps/_payment_panel.html.haml
- app/views/pfmps/_payment_requests_history.html.haml
- config/initializers/version.rb
- spec/models/asp/payment_request_spec.rb
- Add montant réel
- Add rib info
> Add info to pfmp show page

- app/assets/stylesheets/application.css
- app/facades/establishment_facade.rb
- app/views/classes/_attributive_decisions_panel.html.haml
- app/views/home/_attributive_decision_form.html.haml
- app/views/home/_home_timeline.html.haml
- app/views/home/home.html.haml
- config/initializers/version.rb
- config/locales/fr.yml
- release dashboards
- waiting on internal comms before merging + deploying
> Release 2.0.0

- lib/asp/entities/dossier.rb
- lib/asp/entities/enregistrement.rb
- lib/asp/entities/entity.rb
- spec/lib/asp/entities/dossier_spec.rb
- spec/lib/asp/entities/enregistrement_spec.rb
- spec/lib/asp/entities/prestadoss_spec.rb
- remove CoordPaie from Individu
- always send individu info
> Always send individu infos with modification = "O" to avoid duplication on ASP's side

- app/controllers/ribs_controller.rb
- app/models/student.rb
- config/initializers/version.rb
- When the student has no current schooling current rib will show as nil, but it should show up as the one from the last establishment
> Fix rib accessor

- app/apis/students_api/fregata/api.rb
- app/apis/students_api/sygne/api.rb
- app/jobs/sync/student_job.rb
- app/models/student.rb
- spec/apis/students_api/fregata/api_spec.rb
Something I did not see the first time is that we dont use the INE to make the request for Fregata.
> Simplify sync code

- app/models/pfmp.rb
- app/models/pfmp_state_machine.rb
- app/views/pfmps/show.html.haml
- config/locales/fr.yml
- spec/models/pfmp_spec.rb
> Afficher clairement la raison du bloquage de la validation d'une PFMP

- app/helpers/insee_code_helper.rb
- app/views/asp/schoolings/_schooling.html.haml
> Fix display ASP for INSEE codes on Schooling page

- app/controllers/concerns/rectifiable.rb
- app/controllers/pfmps_controller.rb
- app/services/pfmp_manager.rb
- config/locales/fr.yml
- spec/requests/pfmps_controller_spec.rb
- spec/services/pfmp_manager_spec.rb
> Improve Indus UX

- app/models/rib.rb
- app/models/student.rb
- app/views/students/show.html.haml
- features/saisie_de_coordonnees_bancaires.feature
- spec/models/rib_spec.rb
- spec/models/student_spec.rb
- spec/rails_helper.rb
- spec/services/asp/mappers/coord_paie_mapper_spec.rb
> Remove archivable? function

- app/views/pfmps/_payment_requests_history.html.haml
> Modification de l'affichage du PRESTADOSS

- app/controllers/students_controller.rb
- app/models/establishment.rb
- app/views/students/search_results.html.haml
- config/initializers/version.rb
- db/schema.rb
- features/recherche.feature
- spec/models/establishment_spec.rb
> Fix student search

- app/views/ribs/_form.html.haml
> Ajout d'un message d'alerte lorsque l'élève est majeur

- app/views/pfmps/_failed_pfmps.html.haml
> Ajouter la classe et élève cliquable dans la liste des paiements non-aboutis

- app/decorators/asp/payment_request_decorator.rb
- app/models/asp/payment_request.rb
- app/views/pfmps/_payment_requests_history.html.haml
- config/locales/fr.yml
> Gestion de l'affichage des ordres de recouvrements

- app/services/payment_request_reprocessor.rb
- spec/services/payment_request_reprocessor_spec.rb
In order to mass relaunch payments blocked for a certain incompletion reason.
> Add reprocessor

- app/models/asp/payment_request_validator.rb
- config/locales/fr.yml
- spec/models/asp/payment_request_validator_spec.rb
Add a security to the validator
> Add a check to the validator to verify pfmp dates

- app/controllers/academic/application_controller.rb
- app/controllers/academic/establishments_controller.rb
- app/models/student.rb
- app/views/academic/application/_academic_map.html.haml
- app/views/academic/establishments/show.html.haml
- config/routes.rb
- spec/factories/academic_users.rb
- spec/requests/academic/establishments_controller_spec.rb
> Add Etab academic singular view for overview of payment states

- app/helpers/application_helper.rb
- app/helpers/classes_helper.rb
- app/helpers/schoolings_helper.rb
- app/views/pfmps/_dates_warning.html.haml
- app/views/pfmps/_form.html.haml
- app/views/pfmps/_pfmp_student_table.html.haml
- app/views/schoolings/confirm_cancellation_decision.html.haml
- app/views/schoolings/confirm_da_extension.haml
- app/views/students/show.html.haml
- features/eleves.feature
- features/step_definitions/perdir_steps.rb
- features/step_definitions/student_steps.rb
- lib/attribute_decision/cancellation.rb
> Affiche les dates de scolarité dans le détail de l'élève et à la saisie d'une PFMP

- app/controllers/ribs_controller.rb
- app/javascript/controllers/iban_controller.js
- app/javascript/controllers/owner_type_controller.js
- app/views/ribs/_form.html.haml
- app/views/ribs/missing.html.haml
- app/views/ribs/owner_type/_owner_type_horizontal.html.haml
- app/views/ribs/owner_type/_owner_type_vertical.html.haml
> Evolution des champs du formulaire de saisie des coordonnées bancaires

- app/controllers/abrogations_controller.rb
- app/helpers/menu_helper.rb
- app/helpers/schoolings_helper.rb
- app/models/asp/payment_request_validator.rb
- app/models/concerns/user_authorisation.rb
- app/models/schooling.rb
- app/views/abrogations/index.html.haml
- app/views/pfmps/_schooling_buttons.html.haml
- app/views/shared/_header.html.haml
- config/locales/fr.yml
- config/locales/tooltips.yml
- config/routes.rb
- features/abrogations.feature
- features/décisions_d_attributions.feature
- features/step_definitions/perdir_steps.rb
- features/step_definitions/student_steps.rb
- spec/models/asp/payment_request_validator_spec.rb
- spec/models/schooling_spec.rb
> Création d'une page dédiée à l'abrogation des DAs
