betagouv/aplypro

.rubocop.yml
app/controllers/pfmps_controller.rb
app/helpers/dsfr_form_builder.rb
app/helpers/translation_helper.rb
app/models/pfmp.rb
app/views/pfmps/new.html.haml
app/views/ribs/new.html.haml
config/locales/fr.yml
spec/models/pfmp_spec.rb

It's looking a bit like spaghetti code at the moment but it does some *massive* heavy-lifting for us (see the new version of the PFMP form).
I'll get a better idea of the interface rewrite when it gets unbearably ugly.

pfmps: improve the DSFR form builder and use it

---

.github/workflows/test.yaml
app/api/student_api.rb
app/api/student_api/base.rb
app/api/student_api/sygne.rb
app/jobs/fetch_students_job.rb
app/models/establishment.rb
features/support/webmock.rb
spec/api/student_api/sygne_spec.rb
spec/api/student_api_spec.rb
spec/factories/establishments.rb
spec/jobs/fetch_students_job_spec.rb
spec/models/establishment_spec.rb

The StudentsApi module acts as an API proxy that routes to the correct student-fetching API with dedicated classes to wrap the fetching, parsing, mapping and saving of the resources.

students: add some indirection to request students

---

app/views/pfmps/_form.html.haml

This will be useful next year so remove the potential confusion until then.

pfmp: don't show the formation selector quite yet

---

app/controllers/principals/omniauth_callbacks_controller.rb
app/models/concerns/identity_mappers/errors.rb
config/locales/fr.yml
features/premiere_connexion.feature
features/step_definitions/perdir_steps.rb

We're piggybacking ActionController's `rescue_from` hook to catch any errors we might potentially throw (safely scoped to our namespace) and redirect with a nicely inferred flash message.
This means a lot of the auth logic can now resort to:
check_something!
check_something_else!
and create+raise any error that comes up without causing a crash on the frontend, and without us losing the error on the backend either.

auth: better handling of exceptions

---

app/models/classe.rb
app/models/student.rb
app/views/classes/index.html.haml
app/views/classes/show.html.haml
app/views/pfmps/_pfmp_student_table.html.haml
app/views/students/show.html.haml
config/locales/fr.yml
features/consultation_des_listes.feature
features/gestion_de_pfmp.feature
features/saisie_de_coordonnees_bancaires.feature

It was noted during user research, having separate "view the class", "view the student", "view the PFMP" actions is confusing and force mouse-travel which no one likes.
Use the `title` attribute to ensure we keep them legible and clear.

ux: use direct links rather than separate "View the X" actions

---

app/models/principal.rb
app/views/home/login.html.haml
config/initializers/devise.rb
config/initializers/omniauth.rb

We've turned on Review Apps on Scalingo which means triggering a new environement to try out the changes in the pull request. It's a great feature, and something that's going to prove very useful in the near future.
Because the review apps are deployed on custom, temporary domains (i.e `aplypro-test-prNUMBER.osc-fr1.scalingo.io`), we cannot use OIDC because the redirect_uris don't match.
Instead, restore the dev strategy and allow <select> to choose the relevant ministry.

auth: customise the dev strategy

---

Dockerfile

Docker is a leftover from the rails template and curl was for the manual node installation.

docker: remove installation of curl and docker

---

app/models/establishment.rb
db/migrate/20231023084115_add_adress_lines_to_establishments.rb
db/schema.rb
spec/factories/establishments.rb

J'ai vu dans [la doc](https://data.education.gouv.fr/api/v1/console/datasets/1.0/fr-en-annuaire-education/) qu'on pouvait avoir 3 champs d'adresse, mais que c'était pas le cas dans le mock. Dans le doute j'ai pris les 3.
J'ai créé une méthode `establishment.full_address` qui build les 3-4 lignes qui composent l'adresse, mais comme je sais pas où le foutre dans la DA je me suis arrêté là.

store establishment's address

---

app/controllers/pfmps_controller.rb
app/controllers/students_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/establishment.rb
app/models/student.rb
db/migrate/20230512084221_create_establishments.rb
db/migrate/20230516161726_create_classes.rb
db/migrate/20230517062450_add_establishment_id_to_principals.rb
db/migrate/20230522131051_create_students.rb
db/migrate/20230522230816_create_pfmps.rb
db/migrate/20230606160103_create_ribs.rb
db/migrate/20230826134628_create_schoolings.rb
db/migrate/20231011223534_create_invitations.rb
db/migrate/20231012102522_create_join_table_establishment_users.rb
db/schema.rb

This is dodgy (re: changing migrations 6 months later) but since we're not live yet we can afford to just blow up the databases and start fresh, which is far more value than trying to maintain integrity over a DB that isn't live yet.

db: restore regular primary keys

---

app/models/classe.rb
features/gestion_de_pfmp.feature
features/step_definitions/perdir_steps.rb

The step used to validate that test was wrong:
`expect(...) <NOTHING>`
which mean we never caught the error, and is a good reminder to USE END-TO-END ASSERTIONS IN END-TO-END TESTS! Check things on the page, not behind the scenes.

pfmp: fix the bulk input

---

db/migrate/20231030135955_add_primary_key_to_establishment_user_roles.rb
db/schema.rb

We initially went with the `create_join_table` helper from ActiveRecord which creates an ID-less table[1] ; that's problematic because we've got extra attributes on the table which might need updating sooner or later.
[1]: https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-create_join_table

user roles: add a primary key

---

app/controllers/pfmps_controller.rb
app/models/concerns/user_authorisation.rb

Since we're also checking authorisation in other places (ex: invitations), it makes sense to disambiguate here. Also avoid the guard-clause style for the check because
```
def check_authorisation
return if you can validate
redirect
end
```
is a lot more confusing than
```
def check_authorisation
if you cannot validate
send you back
end
end
```
that's why you're not human, Rubocop

pfmp: make the authorisation check more explicit

---

app/controllers/invitations_controller.rb
app/models/concerns/user_authorisation.rb
app/views/invitations/index.html.haml
app/views/invitations/new.html.haml
app/views/shared/_flash.html.haml
app/views/shared/_header.html.haml
config/locales/fr.yml
features/invitations.feature
features/profil_autorisé.feature
features/step_definitions/login_steps.rb
features/step_definitions/perdir_steps.rb

Il y a un truc qui me gène avec l'alerte en cas d'échec d'un formulaire :
Son `fr-col-md-6` la rend très petite quand on est déjà dans un conteneur `fr-col-md-6`. Perso je mettrai éventuellement une largeur max à nos alertes, mais je ne lui mettrai pas de largeur en colonnes comme ça, par ce que ça dépend trop du contexte dans lequel on l'ajoute.
Aussi on perd le breadcrumb, mais ça c'est moins grave.

Invitation deletion

---

app/models/student/mappers/base.rb
app/models/student/mappers/fregata.rb
app/models/student/mappers/sygne.rb

J'avais une dernière évolution en plus : 
* la `Base` classe gère tout le biz
* les classes descendantes ne se chargent que d'indiquer la donnée.

Student mapping extra refactor

---

app/views/classes/_attributive_decisions_panel.html.haml
features/décisions_d_attributions.feature

Pour avoir le bouton ready si on décide de disable l'édition de DA pour le lancement, en attendant d'avoir l'adresse des élèves dedans.

disable DA button for launch

---

app/controllers/users/omniauth_callbacks_controller.rb

This error was renamed a while ago but we didn't update the check, which means it was handled gracefully still, but not with the right message.

auth: fix an error mismatch

---

app/models/user.rb

It's not enabled in the Devise initializer but we still want to hide it from the login page.

auth: remove the developer strategy

---

app/controllers/concerns/developer_oidc.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/models/concerns/identity_mappers/base.rb
app/models/concerns/identity_mappers/cas.rb
app/models/concerns/identity_mappers/fim.rb
features/premiere_connexion.feature
features/step_definitions/login_steps.rb
spec/models/concerns/identity_mappers/base_spec.rb
spec/models/concerns/identity_mappers/fim_spec.rb

Some of our personnel (Secrétaire d'État chargé de la Mer) will not have their attributes (like FrEduRneResp) setup correctly, because the FIM auth won't let them.
To remedy that, add a custom "AplyproResp" attribute that can be used to add some UAIs in responsbility for a given user account. This allows us to augment these users and let them access APLyPro despite the missing values.

auth: add some tests and a way to override the FIM attributes

---

app/models/classe.rb
app/models/schooling.rb
spec/models/classe_spec.rb
spec/models/schooling_spec.rb

We might have classes with leftover schoolings from students who left, so ignore these when trying to create bulk PFMPs.

schooling: add a current scope and use it to fix bulk PFMP creation

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/concerns/identity_mappers/base.rb
app/models/concerns/identity_mappers/fim.rb
features/premiere_connexion.feature
features/step_definitions/login_steps.rb
spec/factories/auth.rb
spec/models/concerns/identity_mappers/base_spec.rb
spec/models/concerns/identity_mappers/fim_spec.rb

> Previously we weren't calculating properly: the user's UAIs were valid
responsibilities we'd found, and valid establishments **for which you
had authorisation** from your boss. This means that if you were in the
proper UAI, you'd still get the "we're in private beta" error, whereas
you should get the "no access found for you" error.
>
> This fixes it by introducing plainer methods to deal with UAIs we find
in the identity vector.

Auth fixes

---

app/controllers/users/omniauth_callbacks_controller.rb
features/premiere_connexion.feature
features/step_definitions/perdir_steps.rb

Piggy-backing the previous PR storing OIDC attributes into the User model, we do want to save these as soon as we come back from the auth so we can debug them ourselves.

auth: save users even if they can't get through

---

features/step_definitions/login_steps.rb

We were using randomly-generated UIDs for the MASA fake auth hash, which means faking the auth twice for the same email doesn't work: the UID is different and our User find_or_initialize_by call uses the provider AND the UID, which meant two accounts, one email, no-go.

auth: fix a failing spec for MASA

---

app/controllers/home_controller.rb

We were never supposed to reach the maintenance page if we're not in maintenance but someone has probably bookmarked the page cause it keeps popping up.

maintenance: also handle a wrong maintenance page

---

app/api/student_api/fregata.rb
app/jobs/fetch_students_job.rb
spec/api/student_api/fregata_spec.rb
spec/jobs/fetch_students_job_spec.rb

We *sometimes* get errors from FREGATA with an invalid signature and a code 401. Catch these and bubble them up to the job so they can be instantly retried (that usually does the... job), until we figure out the underlying cause with the MASA team.
Closes #133

fregata: ensure the API bubbles up 401s

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb

You can't do much unauthorised but the app will crash on `current_user` rather than redirect.
Closes #134.

controllers: put everyone behind the authenticated controller

---

db/migrate/20231112172554_remove_current_schooling_id_from_students.rb
db/schema.rb
docker-compose.yml

Problème de compatibilité entre le PostgreSQL 14 de Scalingo et notre dernière migration écrite sur PostgreSQL 16 ; voir le commit pour l'explication détaillée.

db: backport the latest migration to PostgreSQL 14

---

app/api/student_api/sygne.rb
features/support/webmock.rb
spec/support/webmock_helpers.rb

Suite à nos discussions avec Xavier, voici la version corrigée de l'appel à SYGNE qui ne demande que les élèves actifs.

sygne: only request active students

---

app/controllers/users/omniauth_callbacks_controller.rb
features/gestion_de_pfmp.feature
features/recuperation_eleves.feature
features/step_definitions/login_steps.rb

We've got some data issues that are automatically fixed on the next parsing of the students payload.
More broadly, since a lot of personnel is delegated on the app and we were only refreshing when directors connect, it makes sense to do it on anybody's sucessful authentication into the system.

students: refresh listings everything someone connects

---

app/api/student_api.rb

Now that we have DELEG-CE enabled, it means we can get establishments without directors linked to them: if I'm a director I can give access to someone, and they'll connect without me.
Remove the assumption that there is a director to figure out which provider to use.

api: don't rely on directors to figure out which API to call

---

app/models/student/mappers/sygne.rb
spec/models/student/mappers/sygne_spec.rb

Now that we look at the national MEF code (`codeMefRatt`) rather than the specialised one (`codeMef`), it turns out we sometimes get payload without `codeMefRatt`, which makes the parser crash. That crash is handled gracefully and reported into Sentry, but the issue is frequent enough to produce a fix: coercing the mef code into a string before attempting to chop it.

sygne: don't crash on a missing national MEF code

---

app/models/student/mappers/fregata.rb
spec/support/shared/student_mapper.rb

in our parsing logic rewrite some days ago we stepped away (at least we tried) from the temporal aspect of FREGATA because it returns all the schoolings for each student... in the requested establishment.
In other words, we still have to do some "close the previous schooling if necessary" logic in case a new establishment registers the student, which is now properly adressed.
Closes #241

fregata: re-enable students to change establishments

---

app/controllers/students_controller.rb
config/locales/fr.yml
spec/requests/students_controller_spec.rb

We don't display them in the class listing but the URL was still valid to look at the student and operate a mix of operations that will actually affect the new schooling...
Closes #243.

students: disable looking at a student that has left the class

---

config/locales/fr.yml

We received this screenshot, that made me realise we have a missing translation for the `ActiveRecord::RecordInvalid` in `OmniauthCallbacksController`

auth: fix display of RecordInvalid in authentication_failure

---

app/controllers/pfmps_controller.rb
config/locales/fr.yml
spec/requests/pfmps_controller_spec.rb

As seen before, our users heavily rely on the back button of their browser, which means they'll delete things and then go back via the browser, crashing our controller who's expecting valid user paths. Fix like we did before for classes and students.

pfmps: don't crash when trying to access a missing PFMPs

---

app/models/student.rb
spec/factories/students.rb
spec/models/student_spec.rb
spec/rails_helper.rb

Part of our criteria to send a payment forward will include: do we have your bank coordinates and the necessary information required by the ASP (just the address for now, will include birthday/place and everything else later).

student: add with_rib/address scopes

---

app/api/student_api.rb
app/api/student_api/base.rb
app/api/student_api/fregata.rb
app/api/student_api/sygne.rb
app/jobs/fetch_student_address_job.rb
app/jobs/fetch_students_job.rb
app/models/student/mappers/base.rb
db/schema.rb
spec/api/student_api/fregata_spec.rb
spec/api/student_api/sygne_spec.rb
spec/api/student_api_spec.rb
spec/jobs/fetch_students_job_spec.rb
spec/models/student/mappers/fregata_spec.rb
spec/models/student/mappers/sygne_spec.rb
spec/support/shared/student_mapper.rb

ndlr: description tiré de l'unique commit, mais relates to #264 
StudentAPI shouldn't know about what an establishment looks like: it specialises for a certain provider (SYGNE or FREGATA) and then it queries an UAI, that's it.
The job, because it is passed an establishment, can happily deconstruct the right arguments and pass them plain to the StudentAPI. This will pay-off because it's Good Design®, and also because we'll soon have to worry about establishments that need to get students from both sources.
The interface is simpler with the decoupling:
```ruby
StudentApi.api_for("sygne", "123") # can be queried and inspected
StudentApi.api_for("fregata", "123") # idem
StudentApi.api_for(double_sourced_establishment) # how do you inspect?
```

api: decouple the StudentApi from establishments

---

app/models/payment.rb
app/models/payment_state_machine.rb
app/models/student.rb
spec/factories/payments.rb
spec/models/payment_spec.rb
spec/models/pfmp_spec.rb

Here's the idea:
1. pending: the payment is due;
2. ready: the payment is ready to be sent, we have all the info;
3. processing: the payment has been sent;
4. successful: back from the payment gateway;
5. failed: back from the payment gateway.
The hard bits will be defining the logic between all these bits but in terms of abstraction it should be good enough for now (famous last words).

payments: add a "ready" state

---

app/models/student.rb
app/models/student/address_mappers/fregata.rb
app/models/student/address_mappers/sygne.rb
db/migrate/20240104101419_rename_address_fields_for_student.rb
db/schema.rb
spec/factories/students.rb
spec/jobs/fetch_student_address_job_spec.rb
spec/models/student/address_mappers/fregata_spec.rb
spec/models/student/address_mappers/sygne_spec.rb

In order to tackle https://github.com/betagouv/aplypro/issues/337, rename the address fields explicitly to avoid confusion with `birth_country_code` and `birth_city_code` (coming soon).

db: explicitly name the address fields

---

app/controllers/application_controller.rb
app/controllers/establishments_controller.rb
app/controllers/home_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb

du commit:
> I believe (though it's late and my brain is fried) we need to
redirect to the choose-establishment page only if we have a current
user logged in, otherwise we don't really care. Using a single action
with that logic removes the need for filters in other controllers.

establishments: simplify the choose establishment filter logic

---

app/services/asp/entities/personne_physique.rb
app/services/asp/mappers/student_mapper.rb
spec/factories/students.rb
spec/services/asp/entities/personne_physique_spec.rb
spec/services/asp/mappers/student_mapper_spec.rb

Here's the gameplan: we're going to leverage the Active Model API to encode some of the ASP logic into the app rather than doing some on-the-fly mapping.
This means backporting a bunch of the SERAPIS logic to plain old Ruby objects (albeit extending Active Model) that:
1. declare attributes and possible validations ;
2. are able to be instantiated/mapped from our Active Record models ;
3. declare a `to_xml` method that can tack onto an existing builder object.
This should enable some form of validation chain to make sure we don't send garbage over.

asp: add the PersonnePhysique XML entity

---

app/controllers/application_controller.rb
app/controllers/classes_controller.rb
app/controllers/concerns/role_check.rb
app/controllers/establishments_controller.rb
app/controllers/home_controller.rb
app/controllers/invitations_controller.rb
app/controllers/pfmps_controller.rb
app/controllers/ribs_controller.rb
app/controllers/students_controller.rb
app/controllers/users_controller.rb
app/controllers/validations_controller.rb
app/views/classes/_attributive_decisions_panel.html.haml
app/views/home/home.html.haml
app/views/invitations/index.html.haml
app/views/invitations/new.html.haml
app/views/layouts/application.html.haml
app/views/shared/_etab_banner.html.haml
app/views/shared/_header.html.haml
spec/models/schooling_spec.rb

Conventional wisdom frowns upon instance variables, not just in Rails but in the OOP programming world: you should use accessors instead, even if they just point to the thing.
Do exactly that by exposing a `current_establishment` helper that accesses the @current_establishment variable but doesn't expose it to the rest of the world.
Last but not least: I profoundly regretted using the very-French @etab abbreviation so that is now fixed.

app: standardise `current_establishment` instead of @etab

---

app/services/asp/entities/adresse.rb
app/services/asp/entities/coord_paie.rb
app/services/asp/entities/dossier.rb
app/services/asp/entities/enregistrement.rb
app/services/asp/entities/entity.rb
app/services/asp/entities/pers_physique.rb
app/services/asp/entities/prestadoss.rb
app/services/asp/mappers/coord_paie_mapper.rb
app/services/asp/mappers/pers_physique_mapper.rb
app/services/asp/mappers/prestadoss_mapper.rb
spec/rails_helper.rb
spec/services/asp/entities/coord_paie_spec.rb
spec/services/asp/entities/dossier_spec.rb
spec/services/asp/entities/enregistrement_spec.rb
spec/services/asp/entities/entities_integration_spec.rb
spec/services/asp/entities/pers_physique_spec.rb
spec/services/asp/entities/prestadoss_spec.rb
spec/services/asp/mappers/coord_paie_mapper_spec.rb
spec/services/asp/mappers/pers_physique_mapper_spec.rb

Removing the tiny layer of abstraction between our class name (PersonnePhysique) and the actual ASP name (PersPhysique) means less logic and being able to infer the root node automatically which greatly simplifies the XML fragment code. As much as I dislike the abbreviated French names it's still simpler than introducing that extra layer of French-but-correctly-spelled-out-names.

asp: use the exact ASP entities name

---

app/models/concerns/classes_indicators.rb

On utilisait le `with_attributive_decisions` de classe, qui refaisait une jointure de schooling supplémentaire, multipliant ainsi le nombre de DA comptées.

classes: fix nb_attributive_decisions_per_class

---

config/initializers/sentry.rb

We were using the default Sentry sample rate which sends every transaction and error across the wire. It's just an example and they actually recommend adjusting the setting to balance between performance and signal.
Tune down to 10% as this should still get us significant data and reduce the overhead.
Suggested-by: Julien Bouquillon <julien.bouquillon@beta.gouv.fr>

config: tune down the Sentry sample rate

---

app/controllers/users/omniauth_callbacks_controller.rb

Otherwise it's just scraped, which is not helpful or rightful here.

sentry: name the breadcrumbs data more precisely

---

Dockerfile
Gemfile
Gemfile.lock
config/initializers/version.rb

Zipline has some issues with Puma 6/Rails 7[1] which weren't obvious until we upgraded to Puma 6. Use the patched version until the fix is merged to the main repo.
[1]: https://github.com/fringd/zipline/issues/91

gem: use a patched version of Zipline to fix our upgrade to Puma 6

---

app/models/asp/payment_request_state_machine.rb
app/models/student.rb
spec/factories/asp/payment_requests.rb
spec/factories/students.rb
spec/lib/asp/entities/pers_physique_spec.rb
spec/models/asp/payment_request_spec.rb
spec/models/concerns/allowance_checker_spec.rb

There are some details to be clarified, legally, when a student is over 18 and has a RIB that point to their (ex-)legal person.
We don't really know how to handle it quite yet in the UI, so just filter out the requests that target students over 18 with a RIB to someone else's name, and we'll come back to it as soon as we have more info.
Closes https://github.com/betagouv/aplypro/issues/398

payments: block the request when an adult student has an external rib

---

spec/models/pfmp_spec.rb

Refocus and simplify the tests since the actual logic is covered in the AllowanceChecker specs.

pfmp: fix the flaky calculate_amount spec

---

app/jobs/poll_payments_server_job.rb
app/models/asp/errors.rb
lib/asp/file_reader.rb
spec/jobs/poll_payments_server_job_spec.rb

We can always retry the parsing later as long as we've identified the request/response cycle correctly.

payments: ensure we remove the file even if parsing goes wrong

---

db/migrate/20240219100348_add_administrative_number_to_schoolings.rb

This morning we tried to release but the migration took too long to go through the 560K~ records that had to be updated. To circumvent the proble we went around and finished the migration by running the code in a separate worker where Scalingo grants us 40 minutes for a process instead of the 20 in a post-deploy hook (which is when our migrations normally run).
It went fine in a separate process but we don't want the migration to try and update all of these again so also check on `administrative_number: nil` and add some debugging I had earlier, even though it shouldn't print anything but batch 0.

db: ensure we don't re-run through all mono schoolings

---

app/models/pfmp.rb
app/models/stats/base.rb
app/models/stats/count.rb
app/models/stats/indicator/attributive_decisions.rb
app/models/stats/indicator/payments.rb
app/models/stats/indicator/pfmps.rb
app/models/stats/indicator/ribs.rb
app/models/stats/indicator/schoolings.rb
app/models/stats/indicator/students_data.rb
app/models/stats/indicator/validated_pfmps.rb
app/models/stats/indicator/yearly_amounts.rb
app/models/stats/main.rb
app/models/stats/ratio.rb
app/models/stats/sum.rb
app/models/student.rb
spec/factories/mefs.rb
spec/factories/students.rb
spec/models/stats/indicator/attributive_decisions_spec.rb
spec/models/stats/indicator/payments_spec.rb
spec/models/stats/indicator/pfmps_spec.rb
spec/models/stats/indicator/ribs_spec.rb
spec/models/stats/indicator/schoolings_spec.rb
spec/models/stats/indicator/students_data_spec.rb
spec/models/stats/indicator/validated_pfmps_spec.rb
spec/models/stats/indicator/yearly_amounts_spec.rb
spec/models/stats/main_spec.rb
spec/models/stats/shared_contexts.rb

Closes https://github.com/betagouv/aplypro/issues/432
Cette PR viens après la PR de gestion des scolarités fermées par ce qu'autrement les stats ne seront pas cohérentes avec les indicateurs présents dans l'appli, qui pour le moment ne prennent pas en compte les scolarités fermées.

stats: compute stats from production with reusable classes

---

db/migrate/20240228153920_remove_payments.rb

We got:
> [postdeploy-1827] PG::CardinalityViolation: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
> [postdeploy-1827] HINT:  Ensure that no rows proposed for insertion
> within the same command have duplicate constrained values.
when we tried to run the migration because we sometimes have (a bug that will solve itself) two payments per PFMP, which means the mapping would yield duplicate records, which upsets the UPSERT command.
Solve this by uniq-ing the array.

db: avoid trying to upsert a PFMP twice

---

app/models/schooling.rb
lib/attribute_decision_generator.rb
spec/factories/schoolings.rb

I wrote some dumb code that would tap/save! in the wrong order, which mean we had to return `self` always, and we didn't when there was an existing number.

schoolings: simplify the administrative number generation

---

lib/payment_fixer.rb

The script finds all students with multiple PFMPs with a day count (ie. `not_in_state(:pending)`) but then calls the function with `student.pfmps`. Reintroduce the scope to avoid factoring in nil-day-count PFMPs.

payment fixer: scope the multiple PFMPs

---

app/models/concerns/asp/student_file_eligibility_checker.rb
app/models/student.rb
app/services/insee_codes.rb
config/initializers/version.rb
lib/asp/entities/adresse.rb
lib/asp/entities/pers_physique.rb
spec/models/concerns/asp/student_file_eligibility_checker_spec.rb

The logic is "you need a city code if you were born in France"; this was correctly implemented in the ASP code but the
StudentFileEligibilityChecker was being overly strict without it.

asp: students born abroad are eligible without an address city code

---

spec/factories/asp/payment_requests.rb
spec/models/asp/payment_request_spec.rb
spec/services/asp/readers/payments_file_reader_spec.rb

Because a payment request only makes sense in the context of a validated PFMP (mostly because it requires a positive amount), we generate a validated PFMP in the factory. But because of the – legitimate – callback that triggers a payment creation when a PFMP is validated, the chain goes like this:
create(:payment_request, :ready) ->
create(:pfmp, :validated) ->
pfmp.setup_payment! ->
pfmp.payment_requests.create!  # (A)
pfmp.payment_requests << the actual factory request (B)
This means request A is immediately forgotten and create a strange zombie state for the PFMP.
Instead we can use the initialize_with block of FactoryBot to rewire the logic and re-use the payment request that is created as part of the validation request.

payment requests: don't let the factory create duplicate requests

---

lib/asp/entities/.rubocop.yml
lib/asp/entities/dossier.rb
lib/asp/entities/enregistrement.rb
lib/asp/entities/entity.rb
lib/asp/entities/prestadoss.rb
spec/lib/asp/entities/dossier_spec.rb
spec/lib/asp/entities/enregistrement_spec.rb

Reincluding the data might cause some parsing failures on their side, as we've been told in an email:
> Effectivement c'est une erreur peu compréhensible. Pour ajouter une
> prestation dossier sur un dossier, le plus simple est d'envoyer
> l'individu et le dossier avec l'attribut modification=N mais sans
> balises, comme ceci :
> <ENREGISTREMENT idEnregistrement="313">
>   <INDIVIDU idIndividu="702631849" modification="N">
>     <LISTEDOSSIER>
>       <DOSSIER idDoss="704141913" modification="N">
>         <LISTEPRESTADOSS>
>           <PRESTADOSS>
Closes #629.

asp: don't reinclude the data of known ASP entities

---

app/models/establishment.rb
app/services/asp/mappers/prestadoss_mapper.rb
spec/models/establishment_spec.rb

Overseas (la Réunion, Martinique, etc.) are 3-characters long, which we didn't account for previously.

establishment: fix the departement code

---

app/models/establishment.rb
app/services/asp/mappers/prestadoss_mapper.rb
db/migrate/20240402090724_add_department_code_to_establishments.rb
db/schema.rb
spec/factories/establishments.rb
spec/jobs/fetch_establishment_job_spec.rb
spec/models/establishment_spec.rb

Closes #659 
NOTE: pour la correction des données (i.e réhydrater les établissements avec leur code département), je propose qu'on le fasse à la main ce soir, on a 4578 établissements je pense pas que ce soit trop dur. En sachant que les données sont [automatiquement rafraîchies à chaque connexion](https://github.com/betagouv/aplypro/blob/main/app/controllers/users/omniauth_callbacks_controller.rb#L162).
commit:
```
... by directly storing it from the API which already provides a
three-digit, INSEE-compliant, 0-padded department code.
> %w[9740082W 7200011Z 0340045P].map { |uai| EstablishmentApi.fetch!(uai)["records"][0]["fields"]["code_departement"] }
> ["974", "02B", "034"]
> # La Réunion, Haute-Corse, Hérault
```

establishments: fix the department code logic

---

app/services/asp/file_handler.rb
spec/services/asp/file_handler_spec.rb

Closes https://github.com/betagouv/aplypro/issues/682

asp: clarify the filename attribute and fix file_saved? for payments

---

app/models/pfmp.rb
spec/models/pfmp_spec.rb

pfmp: fix the day count validation logic

---

config/environments/production.rb
config/environments/test.rb

So that we can see the errors in Sentry pop up

Raise error on missing translations in production 

---

app/jobs/poll_payments_server_job.rb
app/services/asp/file_handler.rb
features/accueil_status_des_paiements.feature
lib/asp/server.rb
spec/jobs/poll_payments_server_job_spec.rb
spec/services/asp/file_handler_spec.rb

I'm not sure why I wrote the initial version passing a filename rather than an actual File object. Not only that but the call to:
-      handler = ASP::FileHandler.new(File.join(dir, file))
seems to have yielded things like:
"-tmp-aplypro_asp20240411-22-ntjttg-identifiants_generes_nps_ficimport_idp_aplypro_production_20240410164029.csv"
in production which we'll have to fix by hand. This new version is a lot more sane because it iterates through the directory, makes a file object and then feeds it to the handler which now only has a `file` attribute.

asp: pass an actual file object to the file handler

---

app/models/asp/request.rb
config/locales/en.yml
spec/factories/asp/requests.rb
spec/jobs/send_payment_requests_job_spec.rb
spec/models/asp/payment_request_spec.rb
spec/models/asp/request_spec.rb

We've ran into a huge problem with a SendPaymentRequestsJob erroring out, which means Sidekiq retried it a bunch of times. Everything runs in a transaction but that does not stop the job from depositing the file on the ASP server where we can't just take it back if something goes wrong after.
Add a validation to make sure we only create ASP::Requests with ASP::PaymentRequests in ready state, but only do it on create because we might want to send back (`send!(rerun: true)`) some requests that have crashed on the ASP server ie. before rejection or integration, if their validation catches something our XML schema missed.

asp: check the payment requests state before sending

---

app/jobs/poll_payments_server_job.rb

We're too early-stage to confidently and immediately retry this job until it works. If it's failed once there is little chance it will succeed a minute or an hour later.
We might reconsider in the future but just because this job is meant to be run daily doesn't mean we want the whole
auto-retry-exponential-backoff baked in.

jobs: don't retry the PollPaymentsServerJob for now

---

Procfile
app/jobs/poll_payments_server_job.rb
app/jobs/prepare_payment_requests_job.rb
app/jobs/send_payment_requests_job.rb
docker-compose.yml

The payment tasks are quite heavy: sending requires validating 7000+ records with an XSD schema, updating the associated records, and parsing the results alos means downloading big files which results in big downloads + updating up to 100K records (and going through big XML files again).
To avoid getting OOM-killed by Scalingo (which happens in a dedicated container or in a worker), spawn a new worker to clearly handle that side of the product, and we can beef up the specs when it's running in Scalingo, at least for the time being where we deal with huge volumes.

workers: add a dedicated worker for the payments

---

app/controllers/pfmps_controller.rb
app/models/pfmp.rb
config/locales/fr.yml
spec/models/pfmp_spec.rb

Disabling the actions on the frontend only goes so far – and we have some reports of people somehow deleting locked PFMPs so add the check where it belongs.

pfmps: ensure a locked PFMP cannot be destroyed

---

app/services/asp/readers/base.rb
app/services/asp/readers/csv_reader.rb
app/services/asp/readers/payments_file_reader.rb

It comes in handy to use the logic of the readers without necessarily processing them (i.e trying to update/persist some request changes). You might want to inspect an integrations/rejects/payments file without having to download it and look at the raw string, which is the only option at the moment since `process!` is the only entrypoint.
Change this around by having all readers include Enumerable, which is delegated to the underlying "store" which happens to be a CSV object for the integrations/rejects file, or a Nokogiri XML object if we're looking at the payments.
This means they all inherit the Enumerable API which now allows us to go:
```
reader = ASP::Readers::IntegrationsFileReader.new("some file content")
reader.find { |r| r["idIndDoss"] > 1000 } # a strange but valid query …
```

asp: make the readers implement Enumerable

---

app/models/asp/request.rb
app/services/asp/readers/errors.rb
spec/models/asp/request_spec.rb

This gives the API:
```ruby
request = ASP::Request.last
reader = request.inspect_file(:rejects)
reader.count # number of rows
ids = reader.map { |row| row.fields.first } # all request IDs in the file
reader.process! # -> ASP::Readers::Errors::ReadOnlyMode
```

asp: allow inspecting the request files

---

Gemfile
Gemfile.lock

Starting from Ruby 3.4, CSV is its own gem.

gem: include CSV as a gem

---

app/jobs/process_asp_response_file_job.rb

Now that we've extracted the reading job, it's that easy to make it all happen within a transaction that will revert all transitions and whatever partial update might have happened if something goes wrong in the file.
Closes #746.

asp: do the parsing in a transaction

---

spec/factories/classes.rb
spec/models/concerns/pfmp_amount_calculator_spec.rb

And fix the corresponding spec which were relying on an imaginary mef whose factory hardcodes a daily_rate of 1, hence why it "just worked" without updating the amount before.

spec: use real MEFs instead of generating wageless mefs

---

db/migrate/20240503100542_add_type_on_rib.rb

`update` instantiates the model(s) and runs validations, which is bad for two reasons: 1. wildly inefficient as we have thousands of RIBs to update, 2. it will run into the readonly? protection we have on RIBs with active payment requests.

db: fix the RIB type migration

---

db/migrate/20240506155825_add_indices_on_asp_attributes.rb
db/schema.rb

I don't understand why it wasn't done in the first place when we added them but this will
1. ensure integrity because they actually all need to be unique in their scope;
2. hopefully provide a solid performance boost especially in the payments-parsing job which reads thousands of XML records and uses `asp_prestation_dossier_id` to locate the matching record in our database. Right now there is no index so it probably does a full-table scans for each record which is bad. We're swapping hard and getting OOMK on the latest file.
c.f [1]: bc3ba1b4aacfed537a5f4556861ba5bbaf8ecaf5

db: add indices on ASP attributes

---

spec/factories/asp/payment_requests.rb

If we require the file manually on top of the auto-reload (I assume) of the app it causes the code to crash with:
KeyError:
Factory not registered: "asp_reject"
Remove the manual require (they ASP factories are automatically loaded in the rails_helper.rb file) and everything is nice again. If you need to use the specs in dev (creating fake data, etc), then load the ASP factories in your console.
Worst come to worse, you can always include:
require "./mock/factories/asp"
at the top of config/environments/development.rb and have it loaded in your normal console at all times.

spec: don't freak out Guard

---

.buildpacks
Aptfile

From the latest deploy logs:
```
=====> Detected Framework: Apt
-----> Reusing cache
-----> Updating apt caches
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1757 kB]
Fetched 1986 kB in 1s (1785 kB/s)
Reading package lists...
-----> Fetching .debs for libyaml-dev
Reading package lists...
Building dependency tree...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 7 not upgraded.
Need to get 0 B/62.8 kB of archives.
After this operation, 0 B of additional disk space will be used. …
```

scalingo: remove redundant install of libyaml-dev

---

app/jobs/send_payment_requests_job.rb
spec/jobs/send_payment_requests_job_spec.rb

a final number (post-limiting) of 0 payment requests was interpreted by the
raise ASP::Errors::MaxRecordsPerWeekLimitReached if limit.zero?
line, which is valid if you did have payment requests in the first place (and we can't honour it because you've reached the limit), but if you had no payment requests in the first place that's not the case.

jobs: don't raise an error if there are no payment requests ready

---

Procfile
app/jobs/process_asp_response_file_job.rb
app/jobs/send_payment_requests_job.rb
config/initializers/sidekiq.rb

ProcessASPResponseFileJob can't really run concurrently: it always triggers a bunch of updates on the asp_payment_requests.transitions which means PG deadlocks in production.
SendPaymentRequestsJob is also dangerous even though it is already wrapped in a transaction: there's a stack of ready-payment-requests and it needs to be unstacked progressively, not concurrently.
Closes #870.

jobs: run some of the payments job in a single-threaded queue

---

Procfile
app/jobs/prepare_payment_request_job.rb
app/jobs/process_asp_response_file_job.rb
app/jobs/send_payment_requests_job.rb
config/initializers/sidekiq.rb
config/initializers/version.rb

Our sidekiq initializer says "use the single-threaded capsule for the payments_serial queue" but that capsule is used for all workers, and it doesn't seem to care about the -q argument passed to each worke process.
Remove it in the meantime and just disable concurrency (with n=1) on the payments worker, which kinda makes sense because it handles big, unfrequent jobs that are all to do with sending or receiving files from the ASP. We could potentially rename it to asp-worker to make that clearer.
As part of that logic, move the PreparePaymentRequestJob to the normal worker because like the other jobs there it does some API-querying and operates on our app only.

jobs: don't use the capsule feature

---

app/services/asp/mappers/coord_paie_mapper.rb
app/services/asp/rib_name_sanitiser.rb
spec/services/asp/mappers/coord_paie_mapper_spec.rb
spec/services/asp/rib_name_sanitiser_spec.rb

This tries and keeps best of both worlds by performing soft replacements for things we kinda-know-what-they-meant (dashes, apostrophes, etc) but also silently removes anything that's still offending the regexp at the end.
Closes #365.

asp: move out the RIB name sanitisation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/misc.css
app/controllers/stats_controller.rb
app/javascript/application.js
app/models/paid_pfmp.rb
app/views/layouts/application.html.haml
app/views/shared/_shim.html
app/views/stats/index.html.haml
config/importmap.rb
config/initializers/chartkick.rb
config/locales/fr.yml
config/routes.rb
config/schedule.rb
cron.json
db/migrate/20240523061622_create_paid_pfmps.rb
db/schema.rb
db/views/paid_pfmps_v01.sql

Une proposition de weekend de Pâques pour faire une page stats toute bête mais utile avec : 
- [`scenic`](https://github.com/scenic-views/scenic) pour stocker les chiffres intéressants sans casser la DB ;
- [`chartckick`](https://chartkick.com/) pour afficher des choses, mais pas forcément pertinent en vrai.
Le résultat avec un snapshot de prod : 
Bonus (et aussi motivation de base) : 
> Chaque service numérique du réseau beta.gouv.fr est tenu de mesurer son usage et son impact de manière publique sur une page "Stats". Cette mesure permet d'évaluer la pertinence de chaque service, et de vérifier qu'elle apporte réellement de la valeur à ses utilisateurs et utilisatrices. 
– https://beta.gouv.fr/stats/

stats: add an early version of a stats page

---

config/schedule.rb
cron.json

Since PollPaymentsServerJob runs at 7AM, it makes more sense to regenerate the stats at 9AM when all of the processing is (hopefully) done.

cron: move back the public stats generation

---

app/models/application_record.rb
app/models/schooling.rb
app/models/student.rb

Using attribute_names.map(&:to_sym) is slightly too general, it includes the `id` + timestamps (`created_at/updated_at`) which are internal to Rails and should probably never be updated.

models: add a way to indicate udpatable attributes

---

Dockerfile

`.ruby-version`: 3.3.1
`Dockerfile`: 3.3, which automatically gets 3.3.2 today, hence conflict.

docker: make sure we follow the same precision as `.ruby-version`

---

app/models/pfmp.rb
spec/models/concerns/pfmp_amount_calculator_spec.rb
spec/models/pfmp_spec.rb
spec/services/pfmp_manager_spec.rb

goal:
- make sure no total amount of compensation (Pfmps for one mef) can exceed the yearly cap
before:
- store any amount of days per Pfmp and amount, wait on recalculate method call to check and rebalance
after:
- never store any amount that goes over the yearly cap

Add validation for yearly cap

---

app/models/concerns/pfmp_amount_calculator.rb
app/models/pfmp.rb
app/models/pfmp_state_machine.rb
app/services/pfmp_manager.rb
config/initializers/version.rb
spec/models/concerns/pfmp_amount_calculator_spec.rb
spec/models/pfmp_spec.rb
spec/services/pfmp_manager_spec.rb

- Remove the chronological aspect of Pfmps validation: order of validation and reward calculus seems to be irrelevant, seggregating based on time seems to have lead to series of miscalculation
- Rebalance only based on pre-existing Pfmps, simplify logic

Remove temporality of rebalancing

---

app/facades/validations_facade.rb
app/models/schooling.rb
db/migrate/20241104214101_add_indexes_for_establishment_facade.rb
db/schema.rb

Fix performance of this monster for sure by not using IN:
```rb
"schoolings"."student_id" = $1 AND "schoolings"."id" NOT IN (SELECT "schoolings"."id" FROM "schoolings" WHERE "schoolings"."end_date" IS NOT NULL AND "schoolings"."end_date" <= $2) AND "schoolings"."id" IN (SELECT "schoolings"."id" FROM "schoolings" WHERE "schoolings"."removed_at" IS NULL) LIMIT $3
```
and potentially fix/improve this one too:
```rb
SELECT COUNT(*) AS "count_all", "to_state" AS "to_state" FROM (SELECT DISTINCT ON (pfmp_id) * FROM "asp_payment_requests" ORDER BY pfmp_id, created_at DESC) as asp_payment_requests INNER JOIN "pfmps" ON "asp_payment_requests"."pfmp_id" = "pfmps"."id" INNER JOIN "schoolings" ON "pfmps"."schooling_id" = "schoolings"."id" INNER JOIN "classes" ON "schoolings"."classe_id" = …
```

Add indexes and amend facade

---

app/controllers/ribs_controller.rb
app/facades/classe_facade.rb
app/views/classes/show.html.haml
features/1_gestion_des_scolarités.feature
features/anciens_eleves.feature

Seules les actions `Saisir X coordonnée(s) bancaire(s)` et `Saisir une PFMP pour toute la classe` ont été modifiées

Prends uniquement en compte les élèves actifs pour les actions en masse d'une classe

---

app/apis/students_api/fregata/api.rb
app/jobs/sync/student_job.rb
spec/apis/students_api/fregata/api_spec.rb

Pass optional param :uai to still be able to find Students that may have a closed Schooling on our side
OR Should we consider that if their schooling is closed we should not fetch their info? This might be difficult because Fregata uses Establishment listing to give student info and if the schooling is closed the student probably doesnt show up anymore but we still need his/her most up to date data for payments, etc.
🤔

Fix broken student info call for Fregata students

---

app/models/pfmp_state_machine.rb

Sync Student info upon rectification

---

app/views/pfmps/_pfmp_student_table.html.haml
app/views/pfmps/_schooling_buttons.html.haml
lib/attribute_decision/cancellation.rb
lib/attribute_decision/document_generator.rb

- Reduce margin for cancellation decision document to fit on one page
- Release cancellation feature
- Rework action + document links on student pfmp table page show
- Use download styling for dl links from dsfr

Reduce margin for cancellation decision document to fit on one page + Rework student pfmp page

---

app/apis/students_api/fregata/mappers/address_mapper.rb
app/apis/students_api/sygne/mappers/address_mapper.rb
spec/apis/students_api/sygne/mappers/address_mapper_spec.rb

- Lets split all the elements we get from the api on the 2 lines available instead of sticking it on one line

Mitigate address length issues

---

app/views/stats/_map.html.haml
app/views/stats/index.html.haml

Je passais sur la page de stats d'APLyPro, et j'ai eu envie de modifier ça.
C'est un détail, mais ça me frustre les acronymes alors je fait la PR direct :p
(J'ai pas testé en local, j'ai fait ça dans l'éditeur de github).

use PFMP acronyme everywhere on stats page
